# Generated by Django 4.2 on 2023-06-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='brands'),
        ),
    ]
