# Generated by Django 4.2 on 2023-06-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_alter_buyer_email_alter_buyer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
