# Generated by Django 4.2 on 2023-06-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_delete_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('addressline1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('addressline2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('addressline3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('pic', models.ImageField(blank=True, default='', null=True, upload_to='buyers')),
            ],
        ),
    ]
