# Generated by Django 4.2 on 2023-06-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutproducts',
            name='qty',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='checkoutproducts',
            name='total',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
