# Generated by Django 4.2 on 2023-06-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_checkoutproducts_qty_checkoutproducts_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutproducts',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkoutproducts',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
