# Generated by Django 4.2 on 2023-06-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.ImageField(default=-346543164616, upload_to=''),
        ),
    ]
