# Generated by Django 4.2 on 2023-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_buyer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default=-346543164616),
        ),
    ]
